// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okzmwvuabdgltkxxedtz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rem13dnVhYmRnbHRreHhlZHR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDUyMTksImV4cCI6MjA2NDQyMTIxOX0.SLlzbsTsE0YDFT-UfbCQUwGc9Bh-9keMfm118b3sUIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);